# Environment variables defined in a calling workflow are not accessible to this reusable workflow. Refer to the documentation for further details on this limitation.
name: templates_jobs
on:
  workflow_call:
jobs:
  Ubuntu:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3.3.0
    - run: echo "Hello Ubuntu"
      shell: bash
  Windows:
    runs-on: windows-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3.3.0
    - run: echo "Hello Windows"
      shell: bash
